In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
csvm = "Instructions/Resources/hawaii_measurements.csv"
csvs = "Instructions/Resources/hawaii_stations.csv"
mdf = pd.read_csv(csvm).dropna(how="any").reset_index()
sdf = pd.read_csv(csvs).dropna(how="any")

In [3]:
mdf=mdf.rename(columns={"index":"mes_id"})
mdf

       mes_id      station        date  prcp  tobs
0           0  USC00519397  2010-01-01  0.08    65
1           1  USC00519397  2010-01-02  0.00    63
2           2  USC00519397  2010-01-03  0.00    74
3           3  USC00519397  2010-01-04  0.00    76
4           5  USC00519397  2010-01-07  0.06    70
5           6  USC00519397  2010-01-08  0.00    64
6           7  USC00519397  2010-01-09  0.00    68
7           8  USC00519397  2010-01-10  0.00    73
8           9  USC00519397  2010-01-11  0.01    64
9          10  USC00519397  2010-01-12  0.00    61
10         11  USC00519397  2010-01-14  0.00    66
11         12  USC00519397  2010-01-15  0.00    65
12         13  USC00519397  2010-01-16  0.00    68
13         14  USC00519397  2010-01-17  0.00    64
14         15  USC00519397  2010-01-18  0.00    72
15         16  USC00519397  2010-01-19  0.00    66
16         17  USC00519397  2010-01-20  0.00    66
17         18  USC00519397  2010-01-21  0.00    69
18         19  USC00519397  2010-01-22  0.00    67
19         20  USC00519397  2010-01-23  0.00    67
20         21  USC00519397  2010-01-24  0.01    71
21         22  USC00519397  2010-01-25  0.00    67
22         23  USC00519397  2010-01-26  0.04    76
23         24  USC00519397  2010-01-27  0.12    68
24         25  USC00519397  2010-01-28  0.00    72
25         27  USC00519397  2010-01-31  0.03    67
26         28  USC00519397  2010-02-01  0.01    66
27         30  USC00519397  2010-02-04  0.01    69
28         31  USC00519397  2010-02-05  0.00    67
29         32  USC00519397  2010-02-06  0.00    67
...       ...          ...         ...   ...   ...
18073   19513  USC00516128  2017-07-17  0.39    72
18074   19514  USC00516128  2017-07-18  2.40    77
18075   19515  USC00516128  2017-07-19  0.27    74
18076   19516  USC00516128  2017-07-20  0.70    75
18077   19517  USC00516128  2017-07-21  0.10    72
18078   19518  USC00516128  2017-07-22  4.00    72
18079   19519  USC00516128  2017-07-23  0.80    78
18080   19520  USC00516128  2017-07-24  0.84    77
18081   19521  USC00516128  2017-07-25  0.30    79
18082   19522  USC00516128  2017-07-26  0.30    73
18083   19523  USC00516128  2017-07-27  0.00    75
18084   19524  USC00516128  2017-07-28  0.40    73
18085   19525  USC00516128  2017-07-29  0.30    77
18086   19526  USC00516128  2017-07-30  0.30    79
18087   19527  USC00516128  2017-07-31  0.00    74
18088   19529  USC00516128  2017-08-02  0.25    80
18089   19530  USC00516128  2017-08-03  0.06    76
18090   19533  USC00516128  2017-08-07  0.05    78
18091   19534  USC00516128  2017-08-08  0.34    74
18092   19535  USC00516128  2017-08-09  0.15    71
18093   19536  USC00516128  2017-08-10  0.07    75
18094   19538  USC00516128  2017-08-12  0.14    74
18095   19540  USC00516128  2017-08-14  0.22    79
18096   19541  USC00516128  2017-08-15  0.42    70
18097   19542  USC00516128  2017-08-16  0.42    71
18098   19543  USC00516128  2017-08-17  0.13    72
18099   19545  USC00516128  2017-08-19  0.09    71
18100   19547  USC00516128  2017-08-21  0.56    76
18101   19548  USC00516128  2017-08-22  0.50    76
18102   19549  USC00516128  2017-08-23  0.45    76

[18103 rows x 5 columns]

In [4]:
sdf

,station,name,latitude,longitude,elevation
0,USC00519397,"WAIKIKI 717.2, HI US",21.27160,-157.81680,3.0
1,USC00513117,"KANEOHE 838.1, HI US",21.42340,-157.80150,14.6
2,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.52130,-157.83740,7.0
3,USC00517948,"PEARL CITY, HI US",21.39340,-157.97510,11.9
4,USC00518838,"UPPER WAHIAWA 874.3, HI US",21.49920,-158.01110,306.6
5,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5
6,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9
7,USC00511918,"HONOLULU OBSERVATORY 702.2, HI US",21.31520,-157.99920,0.9
8,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.33310,-157.80250,152.4

In [5]:
mdf.to_csv("clean_hawaii_measurements.csv",index=False)
sdf.to_csv("clean_hawaii_stations.csv",index=False)